# Generated by Django 3.1.7 on 2021-03-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='class_preferences',
            field=models.ManyToManyField(through='database.CoursePreference', to='database.Course'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='room_preferences',
            field=models.ManyToManyField(through='database.RoomPreference', to='database.Room'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='time_preferences',
            field=models.ManyToManyField(through='database.TimeblockPreference', to='database.Timeblock'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
