# Generated by Django 3.1.7 on 2021-03-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenceform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
