# Generated by Django 3.1.6 on 2021-03-08 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name_plural': 'registrations'},
        ),
    ]
