# Generated by Django 3.1.7 on 2021-03-25 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenceform',
            name='is_taking_responses',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='preferenceform',
            name='set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_form', to='database.modelset'),
        ),
        migrations.AlterField(
            model_name='preferenceformentry',
            name='preference_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='database.preferenceform'),
        ),
    ]
