# Generated by Django 3.1.7 on 2021-04-01 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferenceformentry',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='preferenceformentry',
            name='preference_form',
        ),
        migrations.DeleteModel(
            name='PreferenceForm',
        ),
        migrations.DeleteModel(
            name='PreferenceFormEntry',
        ),
    ]
