# Generated by Django 3.1.6 on 2021-03-01 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeblock',
            name='schedule',
        ),
        migrations.AddField(
            model_name='section',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.schedule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='end_hour',
            field=models.IntegerField(choices=[(0, '00'), (1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')]),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='end_minutes',
            field=models.IntegerField(choices=[(0, '00'), (5, '05'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50'), (55, '55')]),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='start_hour',
            field=models.IntegerField(choices=[(0, '00'), (1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')]),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='start_minutes',
            field=models.IntegerField(choices=[(0, '00'), (5, '05'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50'), (55, '55')]),
        ),
    ]
