# Generated by Django 3.2 on 2021-05-02 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210422_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('color', models.SmallIntegerField(choices=[(1, 'Red'), (2, 'Green'), (3, 'Blue')])),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='database.section')),
            ],
        ),
    ]
