# Generated by Django 3.1.7 on 2021-04-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('database', '0002_modelset_obj_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='course',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='other_course',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='timeblock',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='user',
        ),
        migrations.AddField(
            model_name='preference',
            name='object_1_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_1_content_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='preference',
            name='object_1_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='object_2_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_2_content_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='preference',
            name='object_2_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelset',
            name='obj_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'database'), ('model', 'course')), models.Q(('app_label', 'database'), ('model', 'student')), models.Q(('app_label', 'database'), ('model', 'preference')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
