# Generated by Django 3.2 on 2021-04-22 23:22

import database.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210416_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.IntegerField(validators=[database.validators.max_integer_validator]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.IntegerField(default=2021, validators=[database.validators.year_validator]),
        ),
    ]
