# Generated by Django 3.1.7 on 2021-03-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210315_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='overlap_preferences',
            field=models.ManyToManyField(blank=True, related_name='_course_overlap_preferences_+', through='database.OverlapPreference', to='database.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='room_preferences',
            field=models.ManyToManyField(blank=True, related_name='_course_room_preferences_+', through='database.RoomPreference', to='database.Room'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_preferences',
            field=models.ManyToManyField(blank=True, related_name='_course_time_preferences_+', through='database.TimeblockPreference', to='database.Timeblock'),
        ),
    ]
