# Generated by Django 3.2 on 2021-05-06 01:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_sectionnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionnote',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
