# Generated by Django 3.2.2 on 2021-05-10 19:18

import database.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('database', '0003_sectionnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='object_1_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'database'), ('model', 'course')), models.Q(('app_label', 'accounts'), ('model', 'baseuser')), models.Q(('app_label', 'database'), ('model', 'timeblock')), models.Q(('app_label', 'database'), ('model', 'section')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_1_content_type', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='object_2_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'database'), ('model', 'course')), models.Q(('app_label', 'accounts'), ('model', 'baseuser')), models.Q(('app_label', 'database'), ('model', 'timeblock')), models.Q(('app_label', 'database'), ('model', 'section')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_2_content_type', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='sectionnote',
            name='color',
            field=models.CharField(choices=[('#FFFFFF', 'White'), ('#C0C0C0', 'Silver'), ('#808080', 'Gray'), ('#000000', 'Black'), ('#FF0000', 'Red'), ('#800000', 'Maroon'), ('#FFFF00', 'Yellow'), ('#808000', 'Olive'), ('#00FF00', 'Lime'), ('#008000', 'Green'), ('#00FFFF', 'Aqua'), ('#008080', 'Teal'), ('#0000FF', 'Blue'), ('#000080', 'Navy'), ('#FF00FF', 'Fuchsia'), ('#800080', 'Purple')], max_length=7),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_standing',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[database.validators.student_id_validator]),
        ),
    ]
