# Generated by Django 3.2 on 2021-05-08 04:55

import database.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_sectionnote_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionnote',
            name='color',
            field=models.SmallIntegerField(choices=[(1, 'Red'), (2, 'Green'), (3, 'Blue')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_standing',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(null=True, unique=True, validators=[database.validators.student_id_validator]),
        ),
    ]
