# Generated by Django 3.2.2 on 2021-05-09 03:03

import database.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20210508_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_standing',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[database.validators.student_id_validator]),
        ),
    ]
