# Generated by Django 3.2.2 on 2021-05-09 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('database', '0006_auto_20210508_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='object_1_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'database'), ('model', 'course')), models.Q(('app_label', 'accounts'), ('model', 'baseuser')), models.Q(('app_label', 'database'), ('model', 'timeblock')), models.Q(('app_label', 'database'), ('model', 'section')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_1_content_type', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='object_2_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'database'), ('model', 'course')), models.Q(('app_label', 'accounts'), ('model', 'baseuser')), models.Q(('app_label', 'database'), ('model', 'timeblock')), models.Q(('app_label', 'database'), ('model', 'section')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_2_content_type', to='contenttypes.contenttype'),
        ),
    ]
