# Generated by Django 3.2.2 on 2021-05-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20210508_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionnote',
            name='color',
            field=models.CharField(choices=[('#FFFFFF', 'White'), ('#C0C0C0', 'Silver'), ('#808080', 'Gray'), ('#000000', 'Black'), ('#FF0000', 'Red'), ('#800000', 'Maroon'), ('#FFFF00', 'Yellow'), ('#808000', 'Olive'), ('#00FF00', 'Lime'), ('#008000', 'Green'), ('#00FFFF', 'Aqua'), ('#008080', 'Teal'), ('#0000FF', 'Blue'), ('#000080', 'Navy'), ('#FF00FF', 'Fuchsia'), ('#800080', 'Purple')], max_length=7),
        ),
    ]
