# Generated by Django 3.1.6 on 2021-03-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CSV_File_Name', models.CharField(max_length=100)),
                ('CSV_File', models.FileField(upload_to='CSVs/files/')),
            ],
        ),
    ]
