# Generated by Django 3.2 on 2021-04-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataingest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSV',
        ),
    ]
