# Generated by Django 3.0.12 on 2021-04-01 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
        ('datacollection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenceform',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_form', to='database.ModelSet'),
        ),
    ]
