# Generated by Django 3.0.12 on 2021-04-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0002_auto_20210401_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenceform',
            name='name',
            field=models.CharField(default='sdde', max_length=100, verbose_name='Form Name'),
            preserve_default=False,
        ),
    ]
